apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "5"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"3"},"creationTimestamp":"2025-03-15T09:23:09Z","generation":3,"name":"survey-web-app","namespace":"default","resourceVersion":"18034","uid":"beeb22f0-f726-459f-a464-462e106c95b3"},"spec":{"progressDeadlineSeconds":600,"replicas":2,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"survey"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"annotations":{"kubectl.kubernetes.io/restartedAt":"2025-03-15T09:56:52Z"},"creationTimestamp":null,"labels":{"app":"survey"}},"spec":{"containers":[{"image":"557690625329.dkr.ecr.us-east-1.amazonaws.com/survey-web-app:latest","imagePullPolicy":"Always","name":"survey-web-app","ports":[{"containerPort":80,"protocol":"TCP"}],"resources":{"limits":{"cpu":"250m","memory":"256Mi"},"requests":{"cpu":"100m","memory":"128Mi"}},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}},"status":{"availableReplicas":2,"conditions":[{"lastTransitionTime":"2025-03-15T09:56:41Z","lastUpdateTime":"2025-03-15T09:56:41Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"},{"lastTransitionTime":"2025-03-15T09:51:09Z","lastUpdateTime":"2025-03-15T09:56:54Z","message":"ReplicaSet \"survey-web-app-66756459fd\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"}],"observedGeneration":3,"readyReplicas":2,"replicas":2,"updatedReplicas":2}}
  creationTimestamp: "2025-03-15T09:23:09Z"
  generation: 5
  name: survey-web-app
  namespace: default
  resourceVersion: "24052"
  uid: beeb22f0-f726-459f-a464-462e106c95b3
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: survey
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2025-03-15T10:31:43Z"
      creationTimestamp: null
      labels:
        app: survey
    spec:
      containers:
      - image: 557690625329.dkr.ecr.us-east-1.amazonaws.com/survey-web-app:latest
        imagePullPolicy: Always
        name: survey-web-app
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits:
            cpu: 250m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2025-03-15T09:56:41Z"
    lastUpdateTime: "2025-03-15T09:56:41Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-03-15T09:51:09Z"
    lastUpdateTime: "2025-03-15T10:31:46Z"
    message: ReplicaSet "survey-web-app-5c54658d47" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 5
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2
